### ISSUE TITLE
pyembed: BUG: SIGSEGV in safe code

### ISSUE THREAD

**Issue by wkschwartz** [indygreg/PyOxidizer#345]
#344 adds a test for the bug that this issue tracks: a segmentation fault coming from safe code:

```rust
let py = {
    let mut config = pyembed::OxidizedPythonInterpreterConfig::default();
    config.interpreter_config.parse_argv = Some(false);
    config.set_missing_path_configuration = false;
    let mut interp = pyembed::MainPythonInterpreter::new(config).unwrap();
    interp.acquire_gil().unwrap()
};
py.import("sys").unwrap();
```

I would expect lifetime bounds to prevent this from compiling.

**Comment by indygreg** [comment]
The bug here is due to `interp` going out of scope and getting dropped. The problem is the value returned by `acquire_gil()` doesn't hold a reference to `MainPythonInterpreter`. So Rust thinks it is OK to drop `MainPythonInterpreter`. It's `drop()` calls `Py_FinalizeEx()`, which destroys the Python interpreter. Then the `py.import()` calls a CPython API on a finalized interpreter, which causes things to blow up.

The solution here will be for `MainPythonInterpreter` to not _leak_ values dependent on `MainPythonInterpreter` without holding a reference to it.

**Comment by wkschwartz** [comment]
I think some arrangement of Rust lifetime bounds on `MainPythonInterpreter`'s `impl` would allow `MainPythonInterpreter`'s methods to return references to objects that themselves do not reference the `MainPythonInterpreter` instance, e.g., a hypothetical `gil_ref(&'a self) -> &'a GILGuard` would have that property. I think the trouble is that 
```rust
fn acquire_gil(&mut self) -> Result<Python<'python>, &'static str>
```
returns a caller-owned `Python` value with **unbound** lifetime `'python`. Maybe it would suffice to rewrite the signature as follows:
```rust
fn acquire_gil(&'a mut self) -> Result<Python<'python>, &'static str>
    where 'a: 'python,
```

**Comment by indygreg** [comment]
Yeah, we can definitely do better than what I implemented. But what is implemented isn't wrong either. I'll keep this issue open to track improving things.

**Comment by wkschwartz** [comment]
22ebf7d looks good to me! Locally applying 22ebf7d to my test in #344 makes the test pass now, whereas it failed before. If I copy that test into a regular `#[test]`, I get the following feedback from the compiler, which looks like exactly what I would want to see.

```
error[E0597]: `interp` does not live long enough
   --> pyembed/src/interpreter.rs:497:13
    |
492 |         let py = {
    |             -- borrow later stored here
...
497 |             interp.acquire_gil().unwrap()
    |             ^^^^^^ borrowed value does not live long enough
498 |         };
    |         - `interp` dropped here while still borrowed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0597`.
```

The one thing I would urge you to reconsider is rejecting my test from #344. The test you have in 22ebf7d won't fail if there's a regression that reintroduces this bug, but the test in #344 will.

But whether you reopen #344 or not, I think you can close this ticket. Thanks for the fix!
